from pathlib import Path
import json
import os
import pickle

import numpy as np
import pandas as pd
import streamlit as st
from dotenv import load_dotenv
from google import genai


ROOT = Path(__file__).resolve().parent
load_dotenv(ROOT / ".env")

MODELS = {
    "Heart disease": "heart_disease",
    "Diabetes": "diabetes_dataset",
    "Lung disease": "lung_disease_data",
    "Infectious disease / symptoms": "health_dataset",
}

st.set_page_config(page_title="Medical ML Prediction", page_icon="", layout="wide")


@st.cache_resource(show_spinner="Loading the Week 2 pickle model...")
def load_model(dataset_label: str):
    dataset_stem = MODELS[dataset_label]
    model_dir = ROOT / "artifacts" / "models"
    model_path = model_dir / f"{dataset_stem}.pkl"
    if not model_path.exists():
        raise FileNotFoundError(
            "No pickle model was found. Run the Week 2 notebook first so it creates "
            f"{model_path}"
        )
    with model_path.open("rb") as handle:
        bundle = pickle.load(handle)

    if not isinstance(bundle, dict) or "pipeline" not in bundle or "feature_schema" not in bundle:
        raise ValueError(
            "The pickle file does not contain the expected model bundle. "
            "Re-run the Week 2 notebook to generate the current .pkl format."
        )

    return {
        **bundle,
        "model_path": model_path,
        "scores": bundle.get("scores", {}),
    }


def make_input_form(model_info: dict):
    values = {}
    st.subheader("Structured and text inputs")
    st.caption("Inputs and field types are loaded from the Week 2 pickle model bundle.")

    for index, (column, info) in enumerate(model_info["feature_schema"].items()):
        label = str(column)
        if info["kind"] == "numeric":
            minimum = float(info["min"])
            maximum = float(info["max"])
            default = float(info["default"])
            if not np.isfinite(minimum):
                minimum = -1e6
            if not np.isfinite(maximum):
                maximum = 1e6
            if minimum == maximum:
                maximum = minimum + 1.0
            values[column] = st.number_input(
                label,
                min_value=minimum,
                max_value=maximum,
                value=min(max(default, minimum), maximum),
                key=f"field_{index}",
            )
        else:
            options = info.get("options", [""]) or [""]
            values[column] = st.selectbox(label, options, key=f"field_{index}")
    return values


def explain_prediction(prediction: dict, text_context: str) -> str:
    fallback = (
        f"Predicted class: {prediction['prediction']}\n\n"
        f"Confidence: {prediction.get('confidence', 'not available')}\n\n"
        "This is a machine-learning output, not a diagnosis. Review the input and consult a qualified professional."
    )
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return fallback
    try:
        client = genai.Client(api_key=api_key)
        request = {"prediction": prediction, "user_context": text_context[:2000]}
        prompt = (
            "Explain this tabular ML prediction cautiously using only the supplied metadata. "
            "Do not diagnose, invent facts, or recommend treatment. State uncertainty and require human review.\n\n"
            + json.dumps(request, default=str)
        )
        response = client.models.generate_content(
            model=os.getenv("GEMINI_MODEL", "gemini-2.0-flash"),
            contents=prompt,
        )
        return response.text
    except Exception as exc:
        return fallback + f"\n\nExplanation service unavailable: {type(exc).__name__}."


st.title("Medical Dataset ML Prediction")
st.write("This app loads the selected disease pickle model generated by the Week 2 notebook. It does not retrain a model or read the training CSV for prediction inputs.")

with st.sidebar:
    st.header("Model settings")
    selected_dataset = st.selectbox("Dataset", list(MODELS))
    st.markdown("**Run locally**")
    st.code("streamlit run app.py", language="bash")
    st.caption("Model, target, classes, feature names, and input settings come from the .pkl bundle.")
    st.caption(f"Gemini API: {'configured' if os.getenv('GEMINI_API_KEY') else 'not configured (using fallback)'}")

try:
    model_info = load_model(selected_dataset)
except Exception as exc:
    st.error(str(exc))
    st.stop()

col_a, col_b = st.columns([2, 1])
with col_b:
    st.metric("Features", f"{len(model_info['columns']):,}")
    st.metric("Model", str(model_info["model_name"]).replace("_", " ").title())
    st.caption(f"Loaded: {model_info['model_path'].name}")
    st.write("Validation balanced accuracy")
    st.json({name: round(score, 4) for name, score in model_info["scores"].items()})

with col_a:
    with st.form("prediction_form"):
        record = make_input_form(model_info)
        text_context = st.text_area(
            "Text context for the explanation layer (optional)",
            placeholder="Add non-identifying notes only. This text is not used as a model feature.",
        )
        submitted = st.form_submit_button("Predict")

if submitted:
    row = pd.DataFrame([record], columns=model_info["columns"])
    pipeline = model_info["pipeline"]
    label = pipeline.predict(row)[0]
    result = {
        "dataset": selected_dataset,
        "prediction": str(label),
        "model": model_info["model_name"],
        "target": model_info["target"],
        "model_file": model_info["model_path"].name,
    }
    if hasattr(pipeline, "predict_proba"):
        probabilities = pipeline.predict_proba(row)[0]
        result["confidence"] = round(float(np.max(probabilities)), 4)
        result["class_probabilities"] = {
            str(cls): round(float(prob), 4)
            for cls, prob in zip(pipeline.classes_, probabilities)
        }

    st.subheader("Prediction")
    st.success(f"Predicted class: {result['prediction']}")
    st.json(result)
    st.subheader("Explanation")
    st.write(explain_prediction(result, text_context))
    st.download_button(
        "Download result JSON",
        data=json.dumps(result, indent=2),
        file_name="prediction_result.json",
        mime="application/json",
    )

st.divider()
st.caption("Educational prototype only. Do not use this output as a diagnosis or as a substitute for qualified professional review.")
